import { Contract } from '../types';

export const contracts: Contract[] = [
  {
    id: 'contract-1',
    farmerId: 'farmer-1',
    buyerId: 'buyer-doga-frost',
    varietyId: 'lady-rosetta',
    plantingDate: '2025-03-15',
    estimatedHarvestDate: '2025-09-20',
    estimatedYieldTon: 45,
    pricePerKg: 0.62,
    paymentCurrency: 'EUR',
  },
  {
    id: 'contract-2',
    farmerId: 'farmer-1',
    buyerId: 'buyer-doga-frost',
    varietyId: 'hermes',
    plantingDate: '2025-03-20',
    estimatedHarvestDate: '2025-09-25',
    estimatedYieldTon: 30,
    pricePerKg: 0.58,
    paymentCurrency: 'EUR',
  },
  {
    id: 'contract-3',
    farmerId: 'farmer-2',
    buyerId: 'buyer-hamburg-export',
    varietyId: 'agria',
    plantingDate: '2025-03-10',
    estimatedHarvestDate: '2025-09-15',
    estimatedYieldTon: 25,
    pricePerKg: 0.72,
    paymentCurrency: 'EUR',
  },
  {
    id: 'contract-4',
    farmerId: 'farmer-2',
    buyerId: 'buyer-nigde-hal',
    varietyId: 'zirve',
    plantingDate: '2025-03-25',
    estimatedHarvestDate: '2025-10-01',
    estimatedYieldTon: 20,
    pricePerKg: 13.0,
    paymentCurrency: 'TRY',
  },
  {
    id: 'contract-5',
    farmerId: 'farmer-3',
    buyerId: 'buyer-ankara-hal',
    varietyId: 'granola',
    plantingDate: '2025-04-01',
    estimatedHarvestDate: '2025-09-28',
    estimatedYieldTon: 60,
    pricePerKg: 13.5,
    paymentCurrency: 'TRY',
  },
  {
    id: 'contract-6',
    farmerId: 'farmer-4',
    buyerId: 'buyer-doga-frost',
    varietyId: 'lady-rosetta',
    plantingDate: '2025-03-18',
    estimatedHarvestDate: '2025-09-22',
    estimatedYieldTon: 35,
    pricePerKg: 0.62,
    paymentCurrency: 'EUR',
  },
  {
    id: 'contract-7',
    farmerId: 'farmer-4',
    buyerId: 'buyer-istanbul-hal',
    varietyId: 'agria',
    plantingDate: '2025-03-12',
    estimatedHarvestDate: '2025-09-18',
    estimatedYieldTon: 28,
    pricePerKg: 14.0,
    paymentCurrency: 'TRY',
  },
  {
    id: 'contract-8',
    farmerId: 'farmer-5',
    buyerId: 'buyer-nigde-hal',
    varietyId: 'marfona',
    plantingDate: '2025-04-05',
    estimatedHarvestDate: '2025-10-05',
    estimatedYieldTon: 18,
    pricePerKg: 12.0,
    paymentCurrency: 'TRY',
  },
];
