import { Farmer } from '../types';

export const farmers: Farmer[] = [
  {
    id: 'farmer-1',
    name: 'Hasan Celik',
    farmName: 'Celik Tarim',
    city: 'Aksaray',
    coordinates: [38.37, 34.03],
    totalAreaHectare: 80,
    varieties: ['lady-rosetta', 'hermes', 'doruk'],
    contractIds: ['contract-1', 'contract-2'],
  },
  {
    id: 'farmer-2',
    name: 'Ahmet Yildiz',
    farmName: 'Yildiz Ciftligi',
    city: 'Nigde',
    coordinates: [37.97, 34.69],
    totalAreaHectare: 45,
    varieties: ['agria', 'innovator', 'zirve'],
    contractIds: ['contract-3', 'contract-4'],
  },
  {
    id: 'farmer-3',
    name: 'Mehmet Kaya',
    farmName: 'Kaya Patates',
    city: 'Nevsehir',
    coordinates: [38.63, 34.72],
    totalAreaHectare: 120,
    varieties: ['granola', 'marabel', 'nigde-sarisi'],
    contractIds: ['contract-5'],
  },
  {
    id: 'farmer-4',
    name: 'Ali Demir',
    farmName: 'Demir Tarimsal',
    city: 'Nigde',
    coordinates: [37.82, 34.55],
    totalAreaHectare: 60,
    varieties: ['lady-rosetta', 'russet-burbank'],
    contractIds: ['contract-6', 'contract-7'],
  },
  {
    id: 'farmer-5',
    name: 'Mustafa Ozturk',
    farmName: 'Ozturk Organik',
    city: 'Aksaray',
    coordinates: [38.22, 33.85],
    totalAreaHectare: 35,
    varieties: ['marfona', 'van-gogh', 'nahita'],
    contractIds: ['contract-8'],
  },
];
