import { PotatoVariety } from '../types';

export const varieties: PotatoVariety[] = [
  {
    id: 'agria',
    name: 'Agria',
    origin: 'imported',
    useType: 'french_fry',
    optimalTempC: [6, 8],
    optimalHumidity: [90, 95],
    optimalCo2ppm: [2000, 4000],
    dormancyDays: 120,
    sproutTriggerTempC: 10,
    ammoniaThresholdPpm: 15,
    ethyleneThresholdPpb: 50,
    marketPriceTRY: 14.5,
    pricesByMarket: { 'Nigde Hal': 14.2, 'Ankara Hal': 15.0, 'Istanbul Hal': 15.8 },
    notes: 'Hollanda orijinli, parmak patates favorisi. Uzun dormancy.',
  },
  {
    id: 'marabel',
    name: 'Marabel',
    origin: 'imported',
    useType: 'table',
    optimalTempC: [5, 7],
    optimalHumidity: [90, 95],
    optimalCo2ppm: [2000, 4000],
    dormancyDays: 100,
    sproutTriggerTempC: 9,
    ammoniaThresholdPpm: 12,
    ethyleneThresholdPpb: 40,
    marketPriceTRY: 12.0,
    pricesByMarket: { 'Nigde Hal': 11.5, 'Ankara Hal': 12.5, 'Istanbul Hal': 13.0 },
    notes: 'Sofralik, sarı etli, yuvarlak. Orta dormancy.',
  },
  {
    id: 'hermes',
    name: 'Hermes',
    origin: 'imported',
    useType: 'crisping',
    optimalTempC: [7, 9],
    optimalHumidity: [88, 93],
    optimalCo2ppm: [2000, 3500],
    dormancyDays: 90,
    sproutTriggerTempC: 11,
    ammoniaThresholdPpm: 14,
    ethyleneThresholdPpb: 45,
    marketPriceTRY: 15.0,
    pricesByMarket: { 'Nigde Hal': 14.8, 'Doga Frost': 15.5, 'Istanbul Hal': 15.2 },
    notes: 'Cipslik, dusuk seker icerigi.',
  },
  {
    id: 'lady-rosetta',
    name: 'Lady Rosetta',
    origin: 'imported',
    useType: 'crisping',
    optimalTempC: [7, 9],
    optimalHumidity: [88, 93],
    optimalCo2ppm: [2000, 3500],
    dormancyDays: 110,
    sproutTriggerTempC: 11,
    ammoniaThresholdPpm: 14,
    ethyleneThresholdPpb: 45,
    marketPriceTRY: 16.0,
    pricesByMarket: { 'Nigde Hal': 15.5, 'Doga Frost': 16.8, 'Istanbul Hal': 15.0 },
    notes: 'Doga Frost favorisi cipslik cesit. HERO demo cesidi.',
  },
  {
    id: 'granola',
    name: 'Granola',
    origin: 'imported',
    useType: 'table',
    optimalTempC: [5, 7],
    optimalHumidity: [90, 95],
    optimalCo2ppm: [2000, 4000],
    dormancyDays: 80,
    sproutTriggerTempC: 9,
    ammoniaThresholdPpm: 12,
    ethyleneThresholdPpb: 40,
    marketPriceTRY: 11.0,
    pricesByMarket: { 'Nigde Hal': 10.5, 'Ankara Hal': 11.5, 'Istanbul Hal': 12.0 },
    notes: 'Almanya orijinli sofralik. Kisa dormancy — erken satilmali.',
  },
  {
    id: 'marfona',
    name: 'Marfona',
    origin: 'imported',
    useType: 'table',
    optimalTempC: [5, 7],
    optimalHumidity: [90, 95],
    optimalCo2ppm: [2000, 4000],
    dormancyDays: 95,
    sproutTriggerTempC: 9,
    ammoniaThresholdPpm: 13,
    ethyleneThresholdPpb: 42,
    marketPriceTRY: 11.5,
    pricesByMarket: { 'Nigde Hal': 11.0, 'Ankara Hal': 12.0, 'Istanbul Hal': 12.5 },
    notes: 'Hollanda, sofralik/salatalik.',
  },
  {
    id: 'innovator',
    name: 'Innovator',
    origin: 'imported',
    useType: 'french_fry',
    optimalTempC: [6, 8],
    optimalHumidity: [90, 95],
    optimalCo2ppm: [2000, 4000],
    dormancyDays: 130,
    sproutTriggerTempC: 10,
    ammoniaThresholdPpm: 15,
    ethyleneThresholdPpb: 50,
    marketPriceTRY: 14.0,
    pricesByMarket: { 'Nigde Hal': 13.5, 'Ankara Hal': 14.5, 'Istanbul Hal': 15.0 },
    notes: 'Parmak patates icin ideal, uzun dormancy.',
  },
  {
    id: 'russet-burbank',
    name: 'Russet Burbank',
    origin: 'imported',
    useType: 'french_fry',
    optimalTempC: [6, 8],
    optimalHumidity: [90, 95],
    optimalCo2ppm: [2000, 4000],
    dormancyDays: 140,
    sproutTriggerTempC: 10,
    ammoniaThresholdPpm: 15,
    ethyleneThresholdPpb: 55,
    marketPriceTRY: 13.5,
    pricesByMarket: { 'Nigde Hal': 13.0, 'Ankara Hal': 14.0, 'Istanbul Hal': 14.5 },
    notes: 'ABD orijinli klasik patates cipsi/fry cesidi. En uzun dormancy.',
  },
  {
    id: 'van-gogh',
    name: 'Van Gogh',
    origin: 'imported',
    useType: 'table',
    optimalTempC: [5, 7],
    optimalHumidity: [90, 95],
    optimalCo2ppm: [2000, 4000],
    dormancyDays: 85,
    sproutTriggerTempC: 9,
    ammoniaThresholdPpm: 12,
    ethyleneThresholdPpb: 40,
    marketPriceTRY: 12.5,
    pricesByMarket: { 'Nigde Hal': 12.0, 'Ankara Hal': 13.0, 'Istanbul Hal': 13.5 },
    notes: 'Hollanda, sari etli sofralik.',
  },
  {
    id: 'shepody',
    name: 'Shepody',
    origin: 'imported',
    useType: 'french_fry',
    optimalTempC: [6, 8],
    optimalHumidity: [88, 93],
    optimalCo2ppm: [2000, 3500],
    dormancyDays: 100,
    sproutTriggerTempC: 10,
    ammoniaThresholdPpm: 14,
    ethyleneThresholdPpb: 48,
    marketPriceTRY: 13.0,
    pricesByMarket: { 'Nigde Hal': 12.5, 'Ankara Hal': 13.5, 'Istanbul Hal': 14.0 },
    notes: 'Kanada orijinli, erken donem fry cesidi.',
  },
  {
    id: 'milva',
    name: 'Milva',
    origin: 'imported',
    useType: 'table',
    optimalTempC: [5, 7],
    optimalHumidity: [90, 95],
    optimalCo2ppm: [2000, 4000],
    dormancyDays: 90,
    sproutTriggerTempC: 9,
    ammoniaThresholdPpm: 12,
    ethyleneThresholdPpb: 40,
    marketPriceTRY: 11.5,
    pricesByMarket: { 'Nigde Hal': 11.0, 'Ankara Hal': 12.0, 'Istanbul Hal': 12.5 },
    notes: 'Sofralik, erken olgunlasan.',
  },
  // --- Yerli cesitler ---
  {
    id: 'nigde-sarisi',
    name: 'Nigde Sarisi',
    origin: 'native',
    useType: 'table',
    optimalTempC: [5, 7],
    optimalHumidity: [88, 93],
    optimalCo2ppm: [2000, 4000],
    dormancyDays: 75,
    sproutTriggerTempC: 8,
    ammoniaThresholdPpm: 11,
    ethyleneThresholdPpb: 38,
    marketPriceTRY: 10.0,
    pricesByMarket: { 'Nigde Hal': 9.5, 'Ankara Hal': 10.5 },
    // TODO: CEO gorusmesinden gercek degerler alinacak
    notes: 'Nigde yerel cesidi. Kisa dormancy, erken satis onceligi.',
  },
  {
    id: 'saruhan',
    name: 'Saruhan',
    origin: 'native',
    useType: 'table',
    optimalTempC: [5, 7],
    optimalHumidity: [88, 93],
    optimalCo2ppm: [2000, 4000],
    dormancyDays: 80,
    sproutTriggerTempC: 8,
    ammoniaThresholdPpm: 11,
    ethyleneThresholdPpb: 38,
    marketPriceTRY: 10.5,
    pricesByMarket: { 'Nigde Hal': 10.0, 'Ankara Hal': 11.0 },
    // TODO: Nigde Patates Arastirma Enstitusu dokumanlarindan guncellenecek
    notes: 'Yerli sofralik cesit.',
  },
  {
    id: 'nahita',
    name: 'Nahita',
    origin: 'native',
    useType: 'table',
    optimalTempC: [5, 7],
    optimalHumidity: [88, 93],
    optimalCo2ppm: [2000, 4000],
    dormancyDays: 85,
    sproutTriggerTempC: 9,
    ammoniaThresholdPpm: 12,
    ethyleneThresholdPpb: 40,
    marketPriceTRY: 10.5,
    pricesByMarket: { 'Nigde Hal': 10.0, 'Ankara Hal': 11.0 },
    // TODO: Nigde Patates Arastirma Enstitusu dokumanlarindan guncellenecek
    notes: 'Nigde Patates Arastirma Enstitusu cesidi.',
  },
  // --- Doga Tohumculuk cesitleri ---
  {
    id: 'zirve',
    name: 'Zirve',
    origin: 'doga_seed',
    useType: 'table',
    optimalTempC: [5, 7],
    optimalHumidity: [90, 95],
    optimalCo2ppm: [2000, 4000],
    dormancyDays: 95,
    sproutTriggerTempC: 9,
    ammoniaThresholdPpm: 13,
    ethyleneThresholdPpb: 42,
    marketPriceTRY: 13.0,
    pricesByMarket: { 'Nigde Hal': 12.5, 'Ankara Hal': 13.5 },
    // TODO: CEO Yakup Karahan gorusmesinden gercek degerler
    notes: 'Doga Tohumculuk tescilli cesit.',
  },
  {
    id: 'doruk',
    name: 'Doruk',
    origin: 'doga_seed',
    useType: 'crisping',
    optimalTempC: [7, 9],
    optimalHumidity: [88, 93],
    optimalCo2ppm: [2000, 3500],
    dormancyDays: 105,
    sproutTriggerTempC: 11,
    ammoniaThresholdPpm: 14,
    ethyleneThresholdPpb: 45,
    marketPriceTRY: 15.5,
    pricesByMarket: { 'Nigde Hal': 15.0, 'Doga Frost': 16.0 },
    // TODO: CEO Yakup Karahan gorusmesinden gercek degerler
    notes: 'Doga Tohumculuk cipslik cesidi.',
  },
];
